[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts-08/=lib/openzeppelin-contracts/contracts"
]
evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
